version: "3.8"
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: trpc-tut
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

